### ISSUE TITLE
Copy and paste in terminal

### ISSUE THREAD

**Issue by bergmul** [pp4rs/2020-uzh-installation-guide#1]
OLD:

!!! tip "Windows Users: Copy and Paste" The 'tradtional' Ctrl + C and Ctrl + v doesn't work with you terminal. To save manually writing stuff in, highlight the text with you cursor, and then in the terminal use your mouses right-click to paste it in.

NEW:

!!! tip "When using a terminal, the 'traditional' copy and paste commands   `Ctrl + C` and `Ctrl + v` as `Ctrl + Key` commands have a special meaning. Copy is instead `Ctrl + Shift + C` and paste is `Ctrl + Shift + V`. Alternatively, you can always right-click and select `Copy` or `Paste`.

**Comment by bergmul** [comment]
UPDATE: I added an error that right click opens a context menu. For me it pastes right away when doing a right-click. Please update the paragraph to reflect this and your experience.

**Comment by lachlandeer** [comment]
Fixed in fb28b7d387a48d673bf772a7bcd17946f9bcc3fe and 1f7e2c7f6195e9b19b1ffe3c4124345b4e5fd9c2
