### ISSUE TITLE
Check Chromedriver expected version

### ISSUE THREAD

**Issue by bergmul** [pp4rs/2020-uzh-installation-guide#3]
The installation guide seems to refer to chromedriver version 2.41 in the download url and in accordance with this `chromedriver --version` returns `ChromeDriver 2.41.578700 (2f1ed5f9343c13f73144538f15c00b370eda6706)`

However the installation guide says the expected output is `ChromeDriver 79.0.3945.36 .....`

Please confirm this is not a typo.

**Comment by lachlandeer** [comment]
forgot to update the url in the code.

fixed in a5007fc12

now deployed online
